### ISSUE TITLE
Most of the vanilla commands don't work anymore as of 0.5.1

### ISSUE THREAD

**Issue by Okabiz** [Boomflex/JustNotEnoughMods2#19]
Commands like /tp /gamemode etc..

My world has cheats ON, created another world to make sure, still doesn't work.

**Comment by Boomflex** [comment]
Hi Okabiz,

Yeah, this was mentioned on my Discord but I have 0 idea where to even start with the issue... I have sent the issue to the clever Dev people on Forge and numerous other Devs but I can't figure it out.

I have been working on it for like 15 hours at this point and still no closer.

I will update this Issue when I find the root cause!

**Comment by jerry1333** [comment]
Change thutperms.json line 8 to true
`"all": true,`

**Comment by Boomflex** [comment]
This will do it, but I am also replacing Thut next update too.

:)
