### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by SpongeRob093** [Boomflex/JustNotEnoughMods2#20]
Hello,
I was playing on the latest version (0.5.1)  of the modpack (before I loaded the game). I was automating all of my machines and found a ridiculous duplication bug with mekanism. 

I have an ultimate crusher with all of the possible upgrades hooked up to my refined storage system; a crafter on the back and ultimate logistical transporter on the top set to pull and pushing into an interface.

After requesting gold dust, the refined system puts the gold in the crusher, processes it and the logistical transporter pulls gold dust out of the machine and into the system... Thats all normal...
The problem is that it leaves the acutual processed gold dust in the output slot, while pulling out dupped gold dust out of the machine as fast as the logistical transporter can handle. Easy to say that in the short time it took me to notice, I had 30k dupped gold dust (works with osmium as well). After I noticed I manually took out the dust from the output slot and the dupping stopped.

If you need more information, I´ll try to respond asap.

**Comment by Boomflex** [comment]
Hi, a known Mekanism bug. 

If you break the machine and replace it, that will stop the dupe from happening. 

Also, the latest pack update which came out 24 hours ago fixes this. 

In the latest mod pack version, 0.5.2, you will notice that most Mekanism blocks will need to be broken and replaced due to a fix they implemented.
